-- PARA LA CARGA DE ARCHIVOS LOCALES
-- SHOW GLOBAL VARIABLES LIKE 'local_infile';
-- SET GLOBAL local_infile=true;
-- mysql --local_infile=1 -u root -p
-- 

/* -------------------------------------------------------------------------- */
/*                          CREATION OF THE DATABASE                          */
/* -------------------------------------------------------------------------- */
DROP DATABASE IF EXISTS CREDITOS;
CREATE DATABASE IF NOT EXISTS CREDITOS;

USE CREDITOS;

-- CREATION OF THE TABLES

-- INSTITUCION: Catalogo del nombre y clave de la 
-- institucion
CREATE TABLE IF NOT EXISTS INSTITUCION (
	INSTITUCION VARCHAR(6) NOT NULL,
	NOMBRE VARCHAR(25) NOT NULL,
	PRIMARY KEY (INSTITUCION)
);

-- TIPO_TASA: Catalogo de la clave del tipo de tasa que se 
-- aplica al credito, y su restriccion
CREATE TABLE IF NOT EXISTS TIPO_TASA (
	TIPO_TASA INTEGER UNSIGNED NOT NULL, 
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (TIPO_TASA)
);

-- REESTRICCION: Catalogo de la clave de reestriccion y su 
-- descripcion
CREATE TABLE IF NOT EXISTS REESTRICCION (
	TIPO_REESTRICCION INTEGER UNSIGNED NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (TIPO_REESTRICCION)
);

-- CLIENTE: Tabla con las caracteristicas de los 
-- acreditados, con caracteristicas como folio, que
-- va permitir ligar al credito, la institucion con 
-- la que tiene el credito, nombre, apellido, salario, 
-- etc...
CREATE TABLE IF NOT EXISTS CLIENTE (
	INSTITUCION VARCHAR(6) NOT NULL,
	FOLIO_CLIENTE VARCHAR(18) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	EDAD INTEGER NOT NULL,
	SALARIO NUMERIC NOT NULL,
	GENERO ENUM('1', '0') NOT NULL,
	EMPLEO ENUM('PUBLICO', 'PRIVADO', 'ASALARIADO') NOT NULL,
	PRIMARY KEY (INSTITUCION, FOLIO_CLIENTE)
);

-- PRODUCTO: Catalogo de productos que presenta las 
-- características de las mismas, como fecha
-- que se comenzo a otorgar, si presenta comision
-- entre otras caracteristicas
CREATE TABLE IF NOT EXISTS PRODUCTO (
	INSTITUCION VARCHAR(6) NOT NULL, 
	ID_PRODUCTO VARCHAR(18) NOT NULL, 
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL, 
	TIPO_CREDITO INTEGER UNSIGNED NOT NULL,
	TIPO_REESTRICCION INTEGER UNSIGNED NOT NULL,  
	TIPO_TASA INTEGER UNSIGNED NOT NULL,
	COMISION INTEGER UNSIGNED NOT NULL,
	FECHA_CONTRATO DATE NOT NULL,
	PRIMARY KEY(INSTITUCION, ID_PRODUCTO)
);

-- CREDITO: Taabla con las caracteristicas de los creditos
-- como saldo, monto exigido, pago realizado, y para poder
-- ligar con los catalogos
CREATE TABLE IF NOT EXISTS CREDITO (
	INSTITUCION VARCHAR(6) NOT NULL,
	FOLIO VARCHAR(50) NOT NULL,
	ID_PRODUCTO VARCHAR(18) NOT NULL,
	FOLIO_CLIENTE VARCHAR(18) NOT NULL,
	SALDO NUMERIC NOT NULL, 
	ATRASOS INTEGER UNSIGNED NOT NULL, 
	MONTO_EXIGIBLE NUMERIC NOT NULL,
	PAGO_REALIZADO NUMERIC NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	PRIMARY KEY (INSTITUCION, FOLIO)
);

/* -------------------------------------------------------------------------- */
/*                             INSERCION DE DATOS                             */
/* -------------------------------------------------------------------------- */
-- INSTITUCION (INSTITUCION, NOMBRE)
INSERT INTO INSTITUCION (INSTITUCION, NOMBRE)
VALUES
    ('40012', 'BANCOMER'),
	('40021', 'HSBC');

-- TIPO_TASA(TIPO_TASA, DESCRIPCION)
INSERT INTO TIPO_TASA(TIPO_TASA, DESCRIPCION)
VALUES 
    (0, 'NO APLICA'),
	(1, 'FIJA'),
	(2, 'VARIABLE'),
	(3, 'MIXTA');

-- REESTRICCION(TIPO_REESTRICCION, DESCRIPCION)
INSERT INTO REESTRICCION(TIPO_REESTRICCION, DESCRIPCION)
VALUES
    (0, 'SIN REESTRICCION'),
	(1, 'PARA EMPLEADOS');

-- CLIENTE(INSTITUCION, FOLIO_CLIENTE, NOMBRE, EDAD, SALARIO, GENERO, EMPLEO)
INSERT INTO CLIENTE(INSTITUCION, FOLIO_CLIENTE, NOMBRE, EDAD, SALARIO, GENERO, EMPLEO)
VALUES 
    ('40012', 'CLIENTE_1', 'PEDRO', 21, 15000, '0', 'ASALARIADO'),
    ('40012', 'CLIENTE_2', 'JUAN', 28, 18000, '0', 'ASALARIADO'),
    ('40012', 'CLIENTE_3', 'LUIS', 34, 20000, '0', 'ASALARIADO');

-- PRODUCTO(INSTITUCION, ID_PRODUCTO, NOMBRE_PRODUCTO, TIPO_CREDITO, TIPO_REESTRICCION, TIPO_TASA, COMISION, FECHA_CONTRATO)
INSERT INTO PRODUCTO(INSTITUCION, ID_PRODUCTO, NOMBRE_PRODUCTO, TIPO_CREDITO, TIPO_REESTRICCION, TIPO_TASA, COMISION, FECHA_CONTRATO)
VALUES
    ('40012', 'PRODUCTO_1', 'PRODUCTO 1', 1, 0, 1, 0, '2022/01/17'),
	('40012', 'PRODUCTO_2', 'PRODUCTO 2', 1, 0, 1, 0, '2022/01/17');

-- CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE,	PAGO_REALIZADO, FECHA_INICIO)
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES
    ('40012', 'ABC1', 'PROD1', 'CLIE1', 10000, 0, 100, 50, '2022/01/17'),
	('40012', 'ABC2', 'PROD2', 'CLIE1', 10000, 0, 100, 50, '2022/01/17'),
	('40012', 'ABC3', 'PROD3', 'CLIE1', 10000, 0, 100, 50, '2022/01/17'),
	('40012', 'ABC4', 'PROD1', 'CLIE2', 10000, 0, 100, 50, '2022/01/17'),
	('40012', 'ABC5', 'PROD2', 'CLIE2', 10000, 0, 100, 50, '2022/01/17'),
	('40012', 'ABC6', 'PROD3', 'CLIE2', 10000, 0, 100, 50, '2022/01/17'),
	('40012', 'ABC7', 'PROD4', 'CLIE2', 10000, 0, 100, 50, '2022/01/17');

LOAD DATA LOCAL INFILE '../data/cliente.csv' INTO TABLE CLIENTE 
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/credito.csv' INTO TABLE CREDITO
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/institucion.csv' INTO TABLE INSTITUCION
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/producto.csv' INTO TABLE PRODUCTO
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/reestriccion.csv' INTO TABLE REESTRICCION
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/tipo_tasa.csv' INTO TABLE TIPO_TASA
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

/* -------------------------------------------------------------------------- */
/*                              SAMPLE OF TABLES                              */
/* -------------------------------------------------------------------------- */

SHOW TABLES;

