/* -------------------------------------------------------------------------- */
/*                                  LOAD DATA                                 */
/* -------------------------------------------------------------------------- */
-- source creationDB.sql

/* -------------------------------------------------------------------------- */
/*                                     TCL                                    */
/* -------------------------------------------------------------------------- */

USE creditos;

/* --------------------------------- Commit --------------------------------- */
START TRANSACTION;

UPDATE CREDITO
SET SALDO = 555, MONTO_EXIGIBLE = 0
WHERE INSTITUCION='40012' AND FOLIO = 'ABC1';

COMMIT;
SELECT * FROM CREDITO;

/* -------------------------------- Rollback -------------------------------- */
START TRANSACTION;

INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES
    ('40012', 'NOM1ABD', 'PROD1', 'CLIE1', 99999999, 0, 100, 50, '2022/01/17'),
	('40012', 'NOM2DFG', 'PROD2', 'CLIE1', -99999, 0, 100, 50, '2022/01/17');

SELECT * FROM CREDITO WHERE FOLIO IN ('NOM1ABD', 'NOM2DFG');
ROLLBACK ;
SELECT * FROM CREDITO WHERE FOLIO IN ('NOM1ABD', 'NOM2DFG');

/* -------------------------------- Savepoint ------------------------------- */
START TRANSACTION;
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC1A', 'PROD1', 'CLIE1', 10000, 0, 100, 50, '2022/01/17');
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC2AB', 'PROD2', 'CLIE1', 10000, 0, 100, 50, '2022/01/17');
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC3B', 'PROD3', 'CLIE1', 10000, 0, 100, 50, '2022/01/17');
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC3ZB', 'PROD3', 'CLIE1', 10000, 0, 100, 50, '2022/01/17');
SAVEPOINT LOTE_1_4;

INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC4CD', 'PROD1', 'CLIE2', 10000, 0, 100, 50, '2022/01/17');
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC5FG', 'PROD2', 'CLIE2', 10000, 0, 100, 50, '2022/01/17');
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC6HI', 'PROD3', 'CLIE2', 10000, 0, 100, 50, '2022/01/17');
INSERT INTO CREDITO(INSTITUCION, FOLIO, ID_PRODUCTO, FOLIO_CLIENTE, SALDO, ATRASOS, MONTO_EXIGIBLE, PAGO_REALIZADO, FECHA_INICIO)
VALUES ('40021', 'ZABC7JK', 'PROD4', 'CLIE2', 10000, 0, 100, 50, '2022/01/17');
SAVEPOINT LOTE_4_8;

ROLLBACK TO LOTE_1_3;






